documentation:
  - changed-files:
      - any-glob-to-any-file: ['docs/**', 'book/**', '**/*.md']

ci:
  - changed-files:
      - any-glob-to-any-file: ['.github/**']

dependencies:
  - changed-files:
      - any-glob-to-any-file: ['Cargo.toml', 'Cargo.lock']
